### ISSUE TITLE
Add option to specify bind address

### ISSUE THREAD

**Issue by ile** [arangodb-helper/arangodb#139] opened 2018-04-18 09:57 UTC
I think arangodb should not listen to `0.0.0.0` when started with `--starter.address`.

I'm starting with `--starter.address=127.0.0.1` to keep arangod safe inside the machine, but arangodb starts listening to `0.0.0.0` and exposes arangod to the outside world. This is a problem.

I'm exposing arangod to the outside world through [stunnel](https://www.stunnel.org/) and keep arangod traffic unencrypted inside the machine.

**Comment by ile** [comment] 2018-04-18 10:14
A question:

Can I run/use arangod asynchronous replication with automatic failover without arangodb starter?

**Comment by ewoutp** [comment] 2018-04-19 07:01
hi @ile 

The `--starter.address` is used to configure the address from which the starter is reachable, used by  other starters. This is (by design) not the address that the starter binds on.
Now if you would bind the starter to 127.0.0.1, it will never be reachable by starters on other machines, rendering it useful for anything other than single server deployment.

Now I can imagine that if you have 2 network interfaces (a public & a private one), it would make sense to bind to only the private one. We'll add an option for that.

**Comment by ewoutp** [comment] 2018-04-19 07:03
About your second question. Sure, you can. The starter makes it easier, but there is no problem in running all the `arangod` instances by yourself.

How to do that is documented here: https://docs.arangodb.com/devel/Manual/Deployment/ActiveFailover/ManualStart.html

Note that this is the "devel" documentation, but it also applies to 3.3.

**Comment by ile** [comment] 2018-04-24 04:36
It seems that the starter still checks the port on 0.0.0.0 (or any interface) even when `--starter.host=127.0.0.1` is set.

Getting this: `2018/04/24 04:25:08 Port 5000 is already in use`

**Comment by ewoutp** [comment] 2018-04-24 05:41
Please send your exact command line used to start the starter and the logs of the starter.

**Comment by ile** [comment] 2018-04-24 05:54
I ran it as: `./arangodb --starter.data-dir=/arangodb-data --starter.mode=activefailover --starter.join=127.0.0.1:8629 --starter.address=127.0.0.1 --starter.port=5000` 

The logs are lost by now though.

I think the check is here: https://github.com/arangodb-helper/arangodb/blob/master/service/port_check.go#L33

This probably means "any": `":%d"`

I removed that check and compiled and it works for me after that.

**Comment by ewoutp** [comment] 2018-04-24 06:40
Fixed in #147

**Closed by ewoutp** 2018-04-24 06:40 UTC
Labels: 1 Feature
