### ISSUE TITLE
arangodb start command bug: different results of different order in the  whole command

### ISSUE THREAD

**Issue by mathsyouth** [arangodb-helper/arangodb#268] opened 2020-10-20 09:25 UTC
## My Environment

* __ArangoDB Version__:        3.6.8
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Cluster
* __Deployment Strategy__:   ArangoDB Starter
* __Configuration__:              3 machines
* __Infrastructure__:               own
* __Operating System__:        Ubuntu 18.04
* __Total RAM in your machine__:        64Gb each
* __Disks in use__:        HDD

## Component, Query & Data

__Affected feature__:
arangodb start command

### Steps to reproduce

1. Run `arangodb start`:

```
ubuntu@Node2:~/arangodb3-3.6.8$ ./bin/arangodb start --server.storage-engine=rocksdb --auth.jwt-secret=./arangodb.secret --starter.data-dir=./data --starter.join arangodb1,arangodb2,arangodb3
2020-10-19T15:45:42+08:00 |INFO| Starting arangodb version 0.14.15, build e32307e in the background component=arangodb
2020-10-19T15:45:42+08:00 |ERRO| Cannot find arangod (expected at /usr/sbin/arangod). component=arangodb

How to solve this:
1 - Install ArangoDB locally or run the ArangoDB starter in docker. (see README for details).
```

2. Run `arangodb start` in the second way:

```
ubuntu@Node2:~/arangodb3-3.6.8$ ./bin/arangodb  --server.storage-engine=rocksdb --auth.jwt-secret=./arangodb.secret --starter.data-dir=./data --starter.join arangodb1,arangodb2,arangodb3 start
2020-10-19T15:48:37+08:00 |INFO| Starting arangodb version 0.14.15, build e32307e in the background component=arangodb
2020-10-19T15:48:37+08:00 |INFO| Waiting for starter API to be available ... component=arangodb
```
The arangodb services are launched successfully in the second way.

### Problem

the order of `start` in the whole command effects the final results

### Expected result

the order of `start` isn't important

**Comment by hesy007** [comment] 2022-05-09 10:41
？？

**Comment by nikita-vanyasin** [comment] 2023-02-08 14:01
@dothebart 
The issue is caused by the fact that shell script is not very smart at parsing command line arguments. It passes arangod path only if 'start' argument is a $1, although it can be at any place in command line: https://github.com/arangodb/oskar/blob/master/binForTarGz/arangodb

With new [PR](https://github.com/arangodb-helper/arangodb/pull/349) merged that will be fixed. But we should think about removing or simplifying this shell script in future.

**Closed** 2023-02-09 06:54 UTC
