### ISSUE TITLE
Starter usability: show arangod log errors

### ISSUE THREAD

**Issue by jsteemann** [arangodb-helper/arangodb#278] opened 2021-02-18 10:47 UTC
When the starter tries to start up arangod, it may do so up to 100 times in a loop.
If it can't start arangod, it will try again and print out some messages to its logs, but it will not show the reason why arangod couldn't be started.

Ideally the starter could show the last few lines of the arangod.log file in case of a startup failure. The starter should know where the log file is, and it could even check if the logfile was changed due to the arangod start. And if so, it could print the last few lines of the log, so the end user does not have to know that there are additional log files, find them, and inspect them.

IMHO this would greatly improve the starter's usability.

**Comment by nikita-vanyasin** [comment] 2022-07-18 08:29
@jsteemann It looks like starter already has this feature: it will print arangod log entries if there was an error while starting it.
Did you have other experience? If yes, can you provide steps to reproduce it?

Overall, I think the main problem is too much of output due to many attempts to restart it again and again. That will be fixed in PR for https://github.com/arangodb-helper/arangodb/issues/99

**Closed** 2022-07-29 11:17 UTC
